title: Jinal Swarnakar


markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "© Jassera"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/me/" 
 - name: "CV"
   link: "Resume.pdf"
 - name: "Contact"
   link: "contact"
 
